	// Текстдравы для игроков
	ContPrize[playerid][0] = CreatePlayerTextDraw(playerid, 169.4216, 126.4166, "LD_BEAT:CHIT"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][0], 20.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][0], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][0], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][0], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][0], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][0], 0);

	ContPrize[playerid][1] = CreatePlayerTextDraw(playerid, 430.8569, 126.4166, "LD_BEAT:CHIT"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][1], 20.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][1], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][1], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][1], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][1], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][1], 0);

	ContPrize[playerid][2] = CreatePlayerTextDraw(playerid, 430.8569, 290.9165, "LD_BEAT:CHIT"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][2], 20.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][2], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][2], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][2], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][2], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][2], 0);

	ContPrize[playerid][3] = CreatePlayerTextDraw(playerid, 169.4216, 290.9165, "LD_BEAT:CHIT"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][3], 20.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][3], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][3], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][3], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][3], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][3], 0);

	ContPrize[playerid][4] = CreatePlayerTextDraw(playerid, 174.7436, 136.3334, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][4], 0.0000, 18.1054);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][4], 184.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][4], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][4], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][4], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][4], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][4], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][4], 0);

	ContPrize[playerid][5] = CreatePlayerTextDraw(playerid, 437.1158, 136.3332, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][5], 0.0000, 18.0585);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][5], 446.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][5], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][5], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][5], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][5], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][5], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][5], 0);

	ContPrize[playerid][6] = CreatePlayerTextDraw(playerid, 183.1770, 132.2500, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][6], 0.0000, 19.2297);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][6], 438.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][6], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][6], 673720575);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][6], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][6], 437918463);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][6], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][6], 0);

	ContPrize[playerid][7] = CreatePlayerTextDraw(playerid, 245.4904, 131.6667, "CONTAINER"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][7], 0.4356, 1.9441);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][7], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][7], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][7], 0);

	ContPrize[playerid][8] = CreatePlayerTextDraw(playerid, 325.1390, 132.8333, "Premium"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][8], 0.4370, 1.7575);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][8], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][8], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][8], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][8], 0);

	ContPrize[playerid][9] = CreatePlayerTextDraw(playerid, 426.8081, 131.6665, "X"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][9], 0.3025, 1.2497);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][9], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][9], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][9], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][9], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][9], 0);
	PlayerTextDrawSetSelectable(playerid, ContPrize[playerid][9], 1);

	ContPrize[playerid][10] = CreatePlayerTextDraw(playerid, 209.8827, 158.5000, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][10], 0.0000, 1.6603);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][10], 255.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][10], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][10], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][10], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][10], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][10], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][10], 0);

	ContPrize[playerid][11] = CreatePlayerTextDraw(playerid, 206.1347, 165.5001, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][11], 0.0000, 5.6427);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][11], 262.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][11], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][11], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][11], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][11], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][11], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][11], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][11], 0);

	ContPrize[playerid][12] = CreatePlayerTextDraw(playerid, 214.5679, 218.5834, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][12], 0.0000, 0.4420);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][12], 254.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][12], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][12], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][12], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][12], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][12], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][12], 0);

	ContPrize[playerid][13] = CreatePlayerTextDraw(playerid, 200.3439, 151.5001, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][13], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][13], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][13], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][13], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][13], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][13], 0);

	ContPrize[playerid][14] = CreatePlayerTextDraw(playerid, 242.9795, 152.0834, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][14], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][14], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][14], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][14], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][14], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][14], 0);

	ContPrize[playerid][15] = CreatePlayerTextDraw(playerid, 243.4476, 204.0000, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][15], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][15], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][15], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][15], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][15], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][15], 0);

	ContPrize[playerid][16] = CreatePlayerTextDraw(playerid, 200.3439, 203.4167, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][16], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][16], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][16], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][16], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][16], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][16], 0);

	ContPrize[playerid][17] = CreatePlayerTextDraw(playerid, 283.9093, 164.9167, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][17], 0.0000, 5.6427);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][17], 340.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][17], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][17], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][17], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][17], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][17], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][17], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][17], 0);

	ContPrize[playerid][18] = CreatePlayerTextDraw(playerid, 292.3427, 159.0832, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][18], 0.0000, 1.6132);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][18], 334.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][18], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][18], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][18], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][18], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][18], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][18], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][18], 0);

	ContPrize[playerid][19] = CreatePlayerTextDraw(playerid, 195.6587, 147.4165, ""); // пусто
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][19], 0);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][19], 80.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][19], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][19], -1);
	PlayerTextDrawFont(playerid, ContPrize[playerid][19], 5);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][19], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][19], 0);
	PlayerTextDrawSetPreviewModel(playerid, ContPrize[playerid][19], 1277);
	PlayerTextDrawSetPreviewRot(playerid, ContPrize[playerid][19], 0.0000, 0.0000, 0.0000, 1.0000);

	ContPrize[playerid][20] = CreatePlayerTextDraw(playerid, 293.2799, 218.5834, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][20], 0.0000, 0.4889);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][20], 331.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][20], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][20], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][20], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][20], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][20], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][20], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][20], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][20], 0);

	ContPrize[playerid][21] = CreatePlayerTextDraw(playerid, 277.6498, 152.0832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][21], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][21], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][21], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][21], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][21], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][21], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][21], 0);

	ContPrize[playerid][22] = CreatePlayerTextDraw(playerid, 321.2225, 152.0832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][22], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][22], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][22], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][22], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][22], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][22], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][22], 0);

	ContPrize[playerid][23] = CreatePlayerTextDraw(playerid, 278.1187, 204.5832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][23], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][23], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][23], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][23], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][23], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][23], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][23], 0);

	ContPrize[playerid][24] = CreatePlayerTextDraw(playerid, 321.2224, 204.5832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][24], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][24], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][24], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][24], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][24], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][24], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][24], 0);

	ContPrize[playerid][25] = CreatePlayerTextDraw(playerid, 362.1524, 166.6667, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][25], 0.0000, 5.0805);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][25], 417.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][25], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][25], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][25], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][25], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][25], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][25], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][25], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][25], 0);

	ContPrize[playerid][26] = CreatePlayerTextDraw(playerid, 369.1799, 212.7500, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][26], 0.0000, 1.1447);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][26], 410.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][26], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][26], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][26], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][26], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][26], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][26], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][26], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][26], 0);

	ContPrize[playerid][27] = CreatePlayerTextDraw(playerid, 368.7113, 159.6667, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][27], 0.0000, 0.3016);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][27], 408.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][27], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][27], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][27], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][27], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][27], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][27], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][27], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][27], 0);

	ContPrize[playerid][28] = CreatePlayerTextDraw(playerid, 355.8930, 153.2500, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][28], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][28], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][28], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][28], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][28], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][28], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][28], 0);

	ContPrize[playerid][29] = CreatePlayerTextDraw(playerid, 398.5285, 153.2498, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][29], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][29], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][29], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][29], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][29], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][29], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][29], 0);

	ContPrize[playerid][30] = CreatePlayerTextDraw(playerid, 355.8930, 204.5832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][30], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][30], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][30], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][30], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][30], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][30], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][30], 0);

	ContPrize[playerid][31] = CreatePlayerTextDraw(playerid, 398.5289, 204.5832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][31], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][31], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][31], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][31], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][31], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][31], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][31], 0);

	ContPrize[playerid][32] = CreatePlayerTextDraw(playerid, 235.1829, 213.3332, "Talon:_+1_EXP(61)"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][32], 0.1994, 0.7599);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][32], 2);
	PlayerTextDrawColor(playerid, ContPrize[playerid][32], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][32], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][32], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][32], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][32], 0);

	ContPrize[playerid][33] = CreatePlayerTextDraw(playerid, 273.4335, 148.0000, ""); // пусто
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][33], 0);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][33], 80.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][33], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][33], -1);
	PlayerTextDrawFont(playerid, ContPrize[playerid][33], 5);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][33], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][33], 0);
	PlayerTextDrawSetPreviewModel(playerid, ContPrize[playerid][33], 1277);
	PlayerTextDrawSetPreviewRot(playerid, ContPrize[playerid][33], 0.0000, 0.0000, 0.0000, 1.0000);

	ContPrize[playerid][34] = CreatePlayerTextDraw(playerid, 312.4893, 212.7498, "Talon:_+1_EXP(61)"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][34], 0.1994, 0.7599);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][34], 2);
	PlayerTextDrawColor(playerid, ContPrize[playerid][34], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][34], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][34], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][34], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][34], 0);

	ContPrize[playerid][35] = CreatePlayerTextDraw(playerid, 351.6766, 148.5832, ""); // пусто
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][35], 0);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][35], 80.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][35], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][35], -1);
	PlayerTextDrawFont(playerid, ContPrize[playerid][35], 5);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][35], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][35], 0);
	PlayerTextDrawSetPreviewModel(playerid, ContPrize[playerid][35], 1277);
	PlayerTextDrawSetPreviewRot(playerid, ContPrize[playerid][35], 0.0000, 0.0000, 0.0000, 1.0000);

	ContPrize[playerid][36] = CreatePlayerTextDraw(playerid, 390.2639, 213.3333, "Talon:_+1_EXP(61)"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][36], 0.1994, 0.7599);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][36], 2);
	PlayerTextDrawColor(playerid, ContPrize[playerid][36], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][36], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][36], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][36], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][36], 0);

	ContPrize[playerid][37] = CreatePlayerTextDraw(playerid, 209.8827, 236.5000, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][37], 0.0000, 1.6603);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][37], 255.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][37], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][37], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][37], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][37], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][37], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][37], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][37], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][37], 0);

	ContPrize[playerid][38] = CreatePlayerTextDraw(playerid, 206.1347, 243.5001, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][38], 0.0000, 5.6427);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][38], 262.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][38], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][38], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][38], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][38], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][38], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][38], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][38], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][38], 0);

	ContPrize[playerid][39] = CreatePlayerTextDraw(playerid, 214.5679, 296.5834, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][39], 0.0000, 0.4420);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][39], 254.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][39], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][39], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][39], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][39], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][39], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][39], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][39], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][39], 0);

	ContPrize[playerid][40] = CreatePlayerTextDraw(playerid, 200.3439, 229.5001, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][40], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][40], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][40], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][40], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][40], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][40], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][40], 0);

	ContPrize[playerid][41] = CreatePlayerTextDraw(playerid, 242.9795, 230.0834, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][41], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][41], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][41], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][41], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][41], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][41], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][41], 0);

	ContPrize[playerid][42] = CreatePlayerTextDraw(playerid, 243.4476, 282.0000, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][42], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][42], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][42], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][42], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][42], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][42], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][42], 0);

	ContPrize[playerid][43] = CreatePlayerTextDraw(playerid, 200.3439, 281.4166, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][43], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][43], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][43], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][43], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][43], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][43], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][43], 0);

	ContPrize[playerid][44] = CreatePlayerTextDraw(playerid, 283.9093, 242.9167, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][44], 0.0000, 5.6427);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][44], 340.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][44], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][44], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][44], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][44], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][44], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][44], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][44], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][44], 0);

	ContPrize[playerid][45] = CreatePlayerTextDraw(playerid, 292.3427, 237.0832, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][45], 0.0000, 1.6132);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][45], 334.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][45], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][45], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][45], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][45], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][45], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][45], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][45], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][45], 0);

	ContPrize[playerid][46] = CreatePlayerTextDraw(playerid, 195.6587, 225.4165, ""); // пусто
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][46], 0);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][46], 80.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][46], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][46], -1);
	PlayerTextDrawFont(playerid, ContPrize[playerid][46], 5);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][46], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][46], 0);
	PlayerTextDrawSetPreviewModel(playerid, ContPrize[playerid][46], 1277);
	PlayerTextDrawSetPreviewRot(playerid, ContPrize[playerid][46], 0.0000, 0.0000, 0.0000, 1.0000);

	ContPrize[playerid][47] = CreatePlayerTextDraw(playerid, 293.2799, 296.5834, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][47], 0.0000, 0.4889);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][47], 331.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][47], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][47], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][47], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][47], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][47], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][47], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][47], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][47], 0);

	ContPrize[playerid][48] = CreatePlayerTextDraw(playerid, 277.6498, 230.0832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][48], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][48], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][48], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][48], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][48], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][48], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][48], 0);

	ContPrize[playerid][49] = CreatePlayerTextDraw(playerid, 321.2225, 230.0832, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][49], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][49], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][49], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][49], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][49], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][49], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][49], 0);

	ContPrize[playerid][50] = CreatePlayerTextDraw(playerid, 278.1187, 282.5831, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][50], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][50], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][50], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][50], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][50], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][50], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][50], 0);

	ContPrize[playerid][51] = CreatePlayerTextDraw(playerid, 321.2224, 282.5831, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][51], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][51], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][51], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][51], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][51], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][51], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][51], 0);

	ContPrize[playerid][52] = CreatePlayerTextDraw(playerid, 362.1524, 244.6667, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][52], 0.0000, 5.0805);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][52], 417.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][52], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][52], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][52], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][52], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][52], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][52], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][52], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][52], 0);

	ContPrize[playerid][53] = CreatePlayerTextDraw(playerid, 369.1799, 290.7500, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][53], 0.0000, 1.1447);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][53], 410.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][53], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][53], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][53], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][53], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][53], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][53], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][53], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][53], 0);

	ContPrize[playerid][54] = CreatePlayerTextDraw(playerid, 368.7113, 237.6667, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][54], 0.0000, 0.3016);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][54], 408.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][54], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][54], -1);
	PlayerTextDrawUseBox(playerid, ContPrize[playerid][54], 1);
	PlayerTextDrawBoxColor(playerid, ContPrize[playerid][54], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][54], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][54], 2);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][54], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][54], 0);

	ContPrize[playerid][55] = CreatePlayerTextDraw(playerid, 355.8930, 231.2500, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][55], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][55], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][55], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][55], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][55], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][55], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][55], 0);

	ContPrize[playerid][56] = CreatePlayerTextDraw(playerid, 398.5285, 231.2498, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][56], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][56], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][56], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][56], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][56], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][56], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][56], 0);

	ContPrize[playerid][57] = CreatePlayerTextDraw(playerid, 355.8930, 282.5831, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][57], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][57], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][57], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][57], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][57], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][57], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][57], 0);

	ContPrize[playerid][58] = CreatePlayerTextDraw(playerid, 398.5289, 282.5831, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][58], 25.0000, 25.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][58], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][58], 269488383);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][58], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][58], 4);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][58], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][58], 0);

	ContPrize[playerid][59] = CreatePlayerTextDraw(playerid, 235.6514, 290.1664, "Talon:_+1_EXP(61)"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][59], 0.1994, 0.7599);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][59], 2);
	PlayerTextDrawColor(playerid, ContPrize[playerid][59], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][59], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][59], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][59], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][59], 0);

	ContPrize[playerid][60] = CreatePlayerTextDraw(playerid, 273.4335, 226.0000, ""); // пусто
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][60], 0);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][60], 80.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][60], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][60], -1);
	PlayerTextDrawFont(playerid, ContPrize[playerid][60], 5);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][60], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][60], 0);
	PlayerTextDrawSetPreviewModel(playerid, ContPrize[playerid][60], 1277);
	PlayerTextDrawSetPreviewRot(playerid, ContPrize[playerid][60], 0.0000, 0.0000, 0.0000, 1.0000);

	ContPrize[playerid][61] = CreatePlayerTextDraw(playerid, 312.4891, 290.7497, "Talon:_+1_EXP(61)"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][61], 0.1994, 0.7599);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][61], 2);
	PlayerTextDrawColor(playerid, ContPrize[playerid][61], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][61], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][61], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][61], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][61], 0);

	ContPrize[playerid][62] = CreatePlayerTextDraw(playerid, 351.6766, 226.5832, ""); // пусто
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][62], 0);
	PlayerTextDrawTextSize(playerid, ContPrize[playerid][62], 80.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][62], 1);
	PlayerTextDrawColor(playerid, ContPrize[playerid][62], -1);
	PlayerTextDrawFont(playerid, ContPrize[playerid][62], 5);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][62], 0);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][62], 0);
	PlayerTextDrawSetPreviewModel(playerid, ContPrize[playerid][62], 1277);
	PlayerTextDrawSetPreviewRot(playerid, ContPrize[playerid][62], 0.0000, 0.0000, 0.0000, 1.0000);

	ContPrize[playerid][63] = CreatePlayerTextDraw(playerid, 389.7953, 290.7500, "Talon:_+1_EXP(61)"); // пусто
	PlayerTextDrawLetterSize(playerid, ContPrize[playerid][63], 0.1994, 0.7599);
	PlayerTextDrawAlignment(playerid, ContPrize[playerid][63], 2);
	PlayerTextDrawColor(playerid, ContPrize[playerid][63], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, ContPrize[playerid][63], 255);
	PlayerTextDrawFont(playerid, ContPrize[playerid][63], 1);
	PlayerTextDrawSetProportional(playerid, ContPrize[playerid][63], 1);
	PlayerTextDrawSetShadow(playerid, ContPrize[playerid][63], 0);