	SharTD_TD[playerid][0] = CreatePlayerTextDraw(playerid, 226.2810, 164.3333, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][0], 0.0000, 10.9370);
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][0], 406.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][0], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, SharTD_TD[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, SharTD_TD[playerid][0], 336860415);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][0], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][0], 0);

	SharTD_TD[playerid][1] = CreatePlayerTextDraw(playerid, 226.2811, 231.4166, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][1], 0.0000, 2.7847);
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][1], 406.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][1], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][1], -1);
	PlayerTextDrawUseBox(playerid, SharTD_TD[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid, SharTD_TD[playerid][1], -833794561);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][1], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][1], 0);

	SharTD_TD[playerid][2] = CreatePlayerTextDraw(playerid, 315.3002, 237.2500, "PRESSED_(~b~_LALT~w~_)"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][2], 0.4000, 1.6000);
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][2], 0.0000, 151.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][2], 2);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][2], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][2], 0);

	SharTD_TD[playerid][3] = CreatePlayerTextDraw(playerid, 245.0219, 166.0833, "YOUR_PROGRESS"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][3], 0.1957, 0.8649);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][3], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][3], -2139062017);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][3], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][3], 0);

	SharTD_TD[playerid][4] = CreatePlayerTextDraw(playerid, 270.7906, 176.5833, "85%%_TO_COMPILE"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][4], 0.2439, 1.2266);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][4], 2);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][4], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][4], 0);

	SharTD_TD[playerid][5] = CreatePlayerTextDraw(playerid, 248.7701, 196.4166, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][5], 0.0000, 1.7540);
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][5], 388.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][5], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][5], -1);
	PlayerTextDrawUseBox(playerid, SharTD_TD[playerid][5], 1);
	PlayerTextDrawBoxColor(playerid, SharTD_TD[playerid][5], 1260594175);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][5], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][5], 0);

	SharTD_TD[playerid][6] = CreatePlayerTextDraw(playerid, 229.8609, 188.2499, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][6], 32.0000, 32.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][6], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][6], 1260594175);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][6], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][6], 4);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][6], 0);

	SharTD_TD[playerid][7] = CreatePlayerTextDraw(playerid, 372.2913, 188.2499, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][7], 32.0000, 32.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][7], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][7], 1260594175);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][7], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][7], 4);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][7], 0);

	SharTD_TD[playerid][8] = CreatePlayerTextDraw(playerid, 245.4900, 196.4166, "Box"); // пусто
	PlayerTextDrawLetterSize(playerid, SharTD_TD[playerid][8], 0.0000, 1.7071);
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][8], 246.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][8], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][8], -1);
	PlayerTextDrawUseBox(playerid, SharTD_TD[playerid][8], 1);
	PlayerTextDrawBoxColor(playerid, SharTD_TD[playerid][8], -16776961);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][8], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][8], 0);

	SharTD_TD[playerid][9] = CreatePlayerTextDraw(playerid, 229.8608, 188.2500, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][9], 32.0000, 32.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][9], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][9], -16776961);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][9], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][9], 4);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][9], 0);

	SharTD_TD[playerid][10] = CreatePlayerTextDraw(playerid, 372.2914, 187.6667, "LD_BEAT:chit"); // пусто
	PlayerTextDrawTextSize(playerid, SharTD_TD[playerid][10], 32.0000, 32.0000);
	PlayerTextDrawAlignment(playerid, SharTD_TD[playerid][10], 1);
	PlayerTextDrawColor(playerid, SharTD_TD[playerid][10], -16776961);
	PlayerTextDrawBackgroundColor(playerid, SharTD_TD[playerid][10], 255);
	PlayerTextDrawFont(playerid, SharTD_TD[playerid][10], 4);
	PlayerTextDrawSetProportional(playerid, SharTD_TD[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, SharTD_TD[playerid][10], 0);