	Shkaf[playerid][26] = CreatePlayerTextDraw(playerid, 320.250000, 138.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][26], 0.000000, 26.907150);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][26], 180.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][26], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][26], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][26], 1);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][26], 0x111111FF);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][26], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][26], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][26], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][26], 0);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][26], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][26], 0);

	if(PI[playerid][pLanguage] == 0) Shkaf[playerid][25] = CreatePlayerTextDraw(playerid, 187.500000, 143.659897, "WAREHOUSE");
	else Shkaf[playerid][25] = CreatePlayerTextDraw(playerid, 187.500000, 143.659897, FixText("ÿ ¿‘"));
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][25], 0.188333, 1.056592);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][25], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][25], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][25], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][25], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][25], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][25], 0);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][25], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][25], 0x00000000);
	PlayerTextDrawFont(playerid, Shkaf[playerid][25], 2);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][25], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][25], 0);

	Shkaf[playerid][24] = CreatePlayerTextDraw(playerid, 320.250000, 162.242859, "usebox");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][24], 0.000000, -0.214150);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][24], 180.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][24], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][24], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][24], 1);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][24], PI[playerid][pColorInv]);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][24], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][24], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][24], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][24], 0);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][24], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][24], 0);

	Shkaf[playerid][23] = CreatePlayerTextDraw(playerid, 238.050003, 351.242859, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][23], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][23], 5.100000, 5.900000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][23], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][23], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][23], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][23], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][23], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][23], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][23], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][23], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][23], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][23], 1);

	Shkaf[playerid][22] = CreatePlayerTextDraw(playerid, 244.150009, 351.242859, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][22], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][22], 5.100000, 5.900000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][22], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][22], 0x333333FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][22], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][22], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][22], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][22], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][22], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][22], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][22], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][22], 1);

	Shkaf[playerid][21] = CreatePlayerTextDraw(playerid, 250.250000, 351.242859, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][21], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][21], 5.100000, 5.900000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][21], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][21], 0x333333FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][21], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][21], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][21], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][21], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][21], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][21], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][21], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][21], 1);

	Shkaf[playerid][20] = CreatePlayerTextDraw(playerid, 256.350006, 351.242859, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][20], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][20], 5.100000, 5.900000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][20], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][20], 0x333333FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][20], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][20], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][20], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][20], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][20], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][20], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][20], 1);

	Shkaf[playerid][18] = CreatePlayerTextDraw(playerid, 185.677078, 364.693237, "");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][18], 0.235416, 1.320740);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][18], 185.677078, 13.207399);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][18], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][18], 0x67B355FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][18], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][18], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][18], 0);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][18], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][18], 0x00000000);
	PlayerTextDrawFont(playerid, Shkaf[playerid][18], 2);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][18], 1);

	Shkaf[playerid][17] = CreatePlayerTextDraw(playerid, 485.250000, 138.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][17], 0.000000, 26.907150);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][17], 318.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][17], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][17], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][17], 1);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][17], 0x111111FF);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][17], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][17], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][17], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][17], 0);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][17], 0);

	if(PI[playerid][pLanguage] == 0) Shkaf[playerid][16] = CreatePlayerTextDraw(playerid, 326.000000, 143.659897, "INVENTORY");
	else  Shkaf[playerid][16] = CreatePlayerTextDraw(playerid, 326.000000, 143.659897, FixText("»Õ¬≈Õ“¿–‹"));
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][16], 0.188333, 1.056592);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][16], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][16], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][16], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][16], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][16], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][16], 0);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][16], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][16], 0x00000000);
	PlayerTextDrawFont(playerid, Shkaf[playerid][16], 2);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][16], 0);

	Shkaf[playerid][15] = CreatePlayerTextDraw(playerid, 485.250000, 162.242859, "usebox");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][15], 0.000000, -0.214150);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][15], 318.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][15], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][15], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][15], 1);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][15], PI[playerid][pColorInv]);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][15], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][15], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][15], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][15], 0);

	Shkaf[playerid][14] = CreatePlayerTextDraw(playerid, 395.899994, 351.242859, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][14], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][14], 5.100000, 5.900000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][14], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][14], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][14], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][14], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][14], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][14], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][14], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][14], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][14], 1);

	Shkaf[playerid][19] = CreatePlayerTextDraw(playerid, 402.000000, 351.242859, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][19], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][19], 5.100000, 5.900000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][19], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][19], 0x333333FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][19], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][19], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][19], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][19], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][19], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][19], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][19], 1);

	Shkaf[playerid][12] = CreatePlayerTextDraw(playerid, 438.500000, 360.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][12], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][12], 42.500000, 19.666666);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][12], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][12], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][12], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][12], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][12], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][12], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][12], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][12], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][12], 1);

	if(PI[playerid][pLanguage] == 0) Shkaf[playerid][11] = CreatePlayerTextDraw(playerid, 459.750000, 364.693237, "CLOSE");
	else Shkaf[playerid][11] = CreatePlayerTextDraw(playerid, 459.750000, 364.693237, FixText("«¿ –€“‹"));
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][11], 0.188333, 1.056592);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][11], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][11], 2);
	PlayerTextDrawColor(playerid, Shkaf[playerid][11], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][11], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][11], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][11], 0);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][11], 0x00000000);
	PlayerTextDrawFont(playerid, Shkaf[playerid][11], 2);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][11], 0);

	Shkaf[playerid][2] = CreatePlayerTextDraw(playerid, 323.000000, 360.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][2], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][2], 42.500000, 19.666666);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][2], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][2], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][2], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][2], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][2], 2);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][2], 0x000000FF);
	PlayerTextDrawFont(playerid, Shkaf[playerid][2], 4);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][2], 1);

	Shkaf[playerid][1] = CreatePlayerTextDraw(playerid, 185.677078, 364.693237, "$0");
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][1], 0.235416, 1.320740);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][1], 248.677078, 13.207399);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][1], 1);
	PlayerTextDrawColor(playerid, Shkaf[playerid][1], 0x67B355FF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][1], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][1], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][1], 0x00000000);
	PlayerTextDrawFont(playerid, Shkaf[playerid][1], 2);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][1], 1);

	if(PI[playerid][pLanguage] == 0) Shkaf[playerid][0] = CreatePlayerTextDraw(playerid, 344.250000, 365.749817, "INVENTORY");
	else Shkaf[playerid][0] = CreatePlayerTextDraw(playerid, 344.250000, 365.749817, FixText("»Õ¬≈Õ“¿–‹"));
	PlayerTextDrawLetterSize(playerid, Shkaf[playerid][0], 0.150666, 0.845274);
	PlayerTextDrawTextSize(playerid, Shkaf[playerid][0], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, Shkaf[playerid][0], 2);
	PlayerTextDrawColor(playerid, Shkaf[playerid][0], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, Shkaf[playerid][0], 0);
	PlayerTextDrawBoxColor(playerid, Shkaf[playerid][0], 0x80808080);
	PlayerTextDrawSetShadow(playerid, Shkaf[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, Shkaf[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, Shkaf[playerid][0], 0x00000000);
	PlayerTextDrawFont(playerid, Shkaf[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid, Shkaf[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, Shkaf[playerid][0], 0);

	ShkafSlot[playerid][0] = CreatePlayerTextDraw(playerid, 184.500000, 164.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][1] = CreatePlayerTextDraw(playerid, 211.000000, 164.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][2] = CreatePlayerTextDraw(playerid, 237.500000, 164.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][3] = CreatePlayerTextDraw(playerid, 264.000000, 164.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][4] = CreatePlayerTextDraw(playerid, 290.500000, 164.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][5] = CreatePlayerTextDraw(playerid, 184.500000, 195.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][6] = CreatePlayerTextDraw(playerid, 211.000000, 195.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][7] = CreatePlayerTextDraw(playerid, 237.500000, 195.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][8] = CreatePlayerTextDraw(playerid, 264.000000, 195.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][9] = CreatePlayerTextDraw(playerid, 290.500000, 195.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][10] = CreatePlayerTextDraw(playerid, 184.500000, 225.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][11] = CreatePlayerTextDraw(playerid, 211.000000, 225.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][12] = CreatePlayerTextDraw(playerid, 237.500000, 225.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][13] = CreatePlayerTextDraw(playerid, 264.000000, 225.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][14] = CreatePlayerTextDraw(playerid, 290.500000, 225.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][15] = CreatePlayerTextDraw(playerid, 184.500000, 256.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][16] = CreatePlayerTextDraw(playerid, 211.000000, 256.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][17] = CreatePlayerTextDraw(playerid, 237.500000, 256.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][18] = CreatePlayerTextDraw(playerid, 264.000000, 256.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][19] = CreatePlayerTextDraw(playerid, 290.500000, 256.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][20] = CreatePlayerTextDraw(playerid, 184.500000, 286.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][21] = CreatePlayerTextDraw(playerid, 211.000000, 286.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][22] = CreatePlayerTextDraw(playerid, 237.500000, 286.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][23] = CreatePlayerTextDraw(playerid, 264.000000, 286.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][24] = CreatePlayerTextDraw(playerid, 290.500000, 286.742859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][25] = CreatePlayerTextDraw(playerid, 184.500000, 317.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][26] = CreatePlayerTextDraw(playerid, 211.000000, 317.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][27] = CreatePlayerTextDraw(playerid, 237.500000, 317.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][28] = CreatePlayerTextDraw(playerid, 264.000000, 317.242859, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlot[playerid][29] = CreatePlayerTextDraw(playerid, 290.500000, 317.242859, "LD_SPAC:white");
	for(new i = 0; i < 30; i++)
	{
	    PlayerTextDrawLetterSize(playerid, ShkafSlot[playerid][i], 0.480000, 1.120000);
	    PlayerTextDrawTextSize(playerid, ShkafSlot[playerid][i], 25.500000, 29.500000);
	    PlayerTextDrawAlignment(playerid, ShkafSlot[playerid][i], 1);
	    PlayerTextDrawColor(playerid, ShkafSlot[playerid][i], 0xFFFFFFFF);
	    PlayerTextDrawUseBox(playerid, ShkafSlot[playerid][i], 0);
	    PlayerTextDrawBoxColor(playerid, ShkafSlot[playerid][i], 0x80808080);
	    PlayerTextDrawSetShadow(playerid, ShkafSlot[playerid][i], 2);
	    PlayerTextDrawSetOutline(playerid, ShkafSlot[playerid][i], 0);
	    PlayerTextDrawBackgroundColor(playerid, ShkafSlot[playerid][i], 0x333333FF);
	    PlayerTextDrawFont(playerid, ShkafSlot[playerid][i], 5);
	    PlayerTextDrawSetProportional(playerid, ShkafSlot[playerid][i], 1);
	    PlayerTextDrawSetSelectable(playerid, ShkafSlot[playerid][i], 1);
	}
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][0] = CreatePlayerTextDraw(playerid, 209.000000, 187.826187, "LD_SPAC:white");
	ShkafSlotKol[playerid][1] = CreatePlayerTextDraw(playerid, 235.500000, 187.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][2] = CreatePlayerTextDraw(playerid, 262.000000, 187.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][3] = CreatePlayerTextDraw(playerid, 288.500000, 187.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][4] = CreatePlayerTextDraw(playerid, 315.000000, 187.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][5] = CreatePlayerTextDraw(playerid, 209.000000, 218.326187, "LD_SPAC:white");
	ShkafSlotKol[playerid][6] = CreatePlayerTextDraw(playerid, 235.500000, 218.326187, "LD_SPAC:white");
	ShkafSlotKol[playerid][7] = CreatePlayerTextDraw(playerid, 262.000000, 218.326187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][8] = CreatePlayerTextDraw(playerid, 288.500000, 218.326187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][9] = CreatePlayerTextDraw(playerid, 315.000000, 218.326187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][10] = CreatePlayerTextDraw(playerid, 209.000000, 248.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][11] = CreatePlayerTextDraw(playerid, 235.500000, 248.826187, "LD_SPAC:white");
	ShkafSlotKol[playerid][12] = CreatePlayerTextDraw(playerid,  262.000000, 248.826187, "LD_SPAC:white");
	ShkafSlotKol[playerid][13] = CreatePlayerTextDraw(playerid, 288.500000, 248.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][14] = CreatePlayerTextDraw(playerid, 315.000000, 248.826187, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][15] = CreatePlayerTextDraw(playerid, 209.000000, 279.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][16] = CreatePlayerTextDraw(playerid, 235.500000, 279.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][17] = CreatePlayerTextDraw(playerid, 262.000000, 279.326202, "LD_SPAC:white");
	ShkafSlotKol[playerid][18] = CreatePlayerTextDraw(playerid, 288.500000, 279.326202, "LD_SPAC:white");
	ShkafSlotKol[playerid][19] = CreatePlayerTextDraw(playerid, 315.000000, 279.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][20] = CreatePlayerTextDraw(playerid, 209.000000, 309.826202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][21] = CreatePlayerTextDraw(playerid, 235.500000, 309.826202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][22] = CreatePlayerTextDraw(playerid, 262.000000, 309.826202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][23] = CreatePlayerTextDraw(playerid, 288.500000, 309.826202, "LD_SPAC:white");
	ShkafSlotKol[playerid][24] = CreatePlayerTextDraw(playerid, 315.000000, 309.826202, "LD_SPAC:white");
	ShkafSlotKol[playerid][25] = CreatePlayerTextDraw(playerid, 209.000000, 340.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][26] = CreatePlayerTextDraw(playerid, 235.500000, 340.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][27] = CreatePlayerTextDraw(playerid, 262.000000, 340.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][28] = CreatePlayerTextDraw(playerid, 288.500000, 340.326202, "LD_SPAC:white");
	///////////////////////////////////////////////////////////////////////////////////////////////
	ShkafSlotKol[playerid][29] = CreatePlayerTextDraw(playerid, 315.000000, 340.326202, "LD_SPAC:white");
	for(new i = 0; i < 30; i++)
	{
	    PlayerTextDrawLetterSize(playerid, ShkafSlotKol[playerid][i], 0.126499, 0.625000);
		PlayerTextDrawTextSize(playerid, ShkafSlotKol[playerid][i], 1280.000000, 1280.000000);
		PlayerTextDrawAlignment(playerid, ShkafSlotKol[playerid][i], 3);
		PlayerTextDrawColor(playerid, ShkafSlotKol[playerid][i], 0xAAAAAAFF);
		PlayerTextDrawUseBox(playerid, ShkafSlotKol[playerid][i], 0);
		PlayerTextDrawBoxColor(playerid, ShkafSlotKol[playerid][i], 0x80808080);
		PlayerTextDrawSetShadow(playerid, ShkafSlotKol[playerid][i], 0);
		PlayerTextDrawSetOutline(playerid, ShkafSlotKol[playerid][i], 1);
		PlayerTextDrawBackgroundColor(playerid, ShkafSlotKol[playerid][i], 0x00000000);
		PlayerTextDrawFont(playerid, ShkafSlotKol[playerid][i], 2);
		PlayerTextDrawSetProportional(playerid, ShkafSlotKol[playerid][i], 1);
		PlayerTextDrawSetSelectable(playerid, ShkafSlotKol[playerid][i], 0);
	}
