    inventoryTextdraw[playerid][0] = CreatePlayerTextDraw(playerid, 629.401672, 101.500000, "usebox");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][0], 0.000000, 27.343161);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][0], 462.601715, 0.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][0], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][0], 0xE1E1E1FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][0], 1);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][0], 0x111111FF);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][0], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][0], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][0], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][0], 0);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][0], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][0], 0);

    inventoryTextdraw[playerid][1] = CreatePlayerTextDraw(playerid, 470.101715, 106.517044, "INVENTORY");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][1], 0.188333, 1.056592);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][1], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][1], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][1], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][1], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][1], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][1], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][1], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][1], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][1], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][1], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][1], 0);

    inventoryTextdraw[playerid][2] = CreatePlayerTextDraw(playerid, 629.401672, 125.099998, "usebox");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][2], 0.000000, -0.214150);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][2], 462.601715, 0.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][2], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][2], 0xE1E1E1FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][2], 1);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][2], 0xBF5656FF);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][2], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][2], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][2], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][2], 0);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][2], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][2], 0);

    inventoryTextdraw[playerid][3] = CreatePlayerTextDraw(playerid, 582.601685, 326.933350, "LD_SPAC:white");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][3], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][3], 42.500000, 19.666666);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][3], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][3], 0xBF5656FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][3], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][3], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][3], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][3], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][3], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][3], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][3], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][3], 1);

    inventoryTextdraw[playerid][4] = CreatePlayerTextDraw(playerid, 603.851685, 331.483734, "CLOSE");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][4], 0.188333, 1.056592);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][4], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][4], 2);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][4], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][4], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][4], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][4], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][4], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][4], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][4], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][4], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][4], 0);

    inventoryTextdraw[playerid][5] = CreatePlayerTextDraw(playerid, 608.101685, 102.466667, "LD_BEAT:chit");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][5], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][5], 17.000000, 19.666666);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][5], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][5], 0x111111FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][5], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][5], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][5], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][5], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][5], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][5], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][5], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][5], 1);

    inventoryTextdraw[playerid][6] = CreatePlayerTextDraw(playerid, 616.601685, 107.017044, "S");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][6], 0.188333, 1.056592);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][6], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][6], 2);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][6], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][6], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][6], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][6], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][6], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][6], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][6], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][6], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][6], 0);

    inventoryTextdraw[playerid][7] = CreatePlayerTextDraw(playerid, 522.351685, 314.100006, "LD_BEAT:chit");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][7], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][7], 8.500000, 9.833333);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][7], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][7], 0xBF5656FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][7], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][7], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][7], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][7], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][7], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][7], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][7], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][7], 0);

    inventoryTextdraw[playerid][8] = CreatePlayerTextDraw(playerid, 531.851685, 314.100006, "LD_BEAT:chit");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][8], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][8], 8.500000, 9.833333);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][8], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][8], 0x333333FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][8], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][8], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][8], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][8], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][8], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][8], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][8], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][8], 1);

    inventoryTextdraw[playerid][9] = CreatePlayerTextDraw(playerid, 541.351685, 314.100006, "LD_BEAT:chit");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][9], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][9], 8.500000, 9.833333);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][9], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][9], 0x333333FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][9], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][9], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][9], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][9], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][9], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][9], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][9], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][9], 1);

    inventoryTextdraw[playerid][10] = CreatePlayerTextDraw(playerid, 550.851685, 314.100006, "LD_BEAT:chit");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][10], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][10], 8.500000, 9.833333);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][10], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][10], 0x333333FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][10], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][10], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][10], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][10], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][10], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][10], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][10], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][10], 1);

    inventoryTextdraw[playerid][11] = CreatePlayerTextDraw(playerid, 560.351685, 314.100006, "LD_BEAT:chit");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][11], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][11], 8.500000, 9.833333);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][11], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][11], 0x1A1A1AFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][11], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][11], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][11], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][11], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][11], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][11], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][11], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][11], 0);

    inventoryTextdraw[playerid][12] = CreatePlayerTextDraw(playerid, 467.101715, 326.933350, "LD_SPAC:white");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][12], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][12], 42.500000, 19.666666);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][12], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][12], 0xBF5656FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][12], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][12], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][12], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][12], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][12], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][12], 4);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][12], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][12], 1);

    inventoryTextdraw[playerid][13] = CreatePlayerTextDraw(playerid, 488.351715, 332.540314, "SECURITY");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][13], 0.150666, 0.845274);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][13], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][13], 2);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][13], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][13], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][13], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][13], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][13], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][13], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][13], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][13], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][13], 0);

    inventoryTextdraw[playerid][14] = CreatePlayerTextDraw(playerid, 462.401703, 101.500000, "usebox");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][14], 0.000000, 27.343161);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][14], 333.500000, 0.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][14], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][14], 0xE1E1E1FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][14], 1);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][14], 0x111111FF);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][14], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][14], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][14], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][14], 0);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][14], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][14], 0);

    inventoryTextdraw[playerid][15] = CreatePlayerTextDraw(playerid, 462.401703, 125.099998, "usebox");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][15], 0.000000, -0.214150);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][15], 333.500000, 0.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][15], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][15], 0xE1E1E1FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][15], 1);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][15], 0xBF5656FF);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][15], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][15], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][15], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][15], 0);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][15], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][15], 0);

    for(new i, buttonNames[][][] = { {"HELP", "онлныэ"}, {"REPORT", "пеонпр"} }; i < 6; i++)
    {
        inventoryTextdraw[playerid][16 + i] = CreatePlayerTextDraw(playerid, 338.000000 + ((41.033905 * (i > 2 ? i - 3 : i)) + (i % 2 ? 19.016937 : 0.0)), 103.466667 + (i % 2 ? 3.517037 : 0.0), i % 2 ? (i < 4 ? buttonNames[i - (i > 1 ? 2 : 1)][SettingData[playerid][sdLanguage]] : !"GPS") : !"LD_SPAC:white");
        PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 0.188333 : 0.480000, i % 2 ? 1.056592 : 1.120000);
        PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 1280.000000 : 38.033894, i % 2 ? 1280.000000 : 17.599998);
        PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 2 : 1);
        PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 0xFFFFFFFF : 0xBF5656FF);
        PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][16 + i], 0);
        PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][16 + i], 0x80808080);
        PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 0 : 2);
        PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][16 + i], 0);
        PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][16 + i], 0x000000FF);
        PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 2 : 4);
        PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][16 + i], 1);
        PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][16 + i], i % 2 ? 0 : 1);
    }

    inventoryTextdraw[playerid][22] = CreatePlayerTextDraw(playerid, 462.401703, 129.100006, "usebox");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][22], 0.000000, 8.897720);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][22], 333.500000, 0.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][22], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][22], 0xE1E1E1FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][22], 1);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][22], 0x1A1A1AFF);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][22], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][22], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][22], 0x000000FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][22], 0);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][22], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][22], 0);
/*
fstd_p[playerid][76] = CreatePlayerTextDraw(playerid, 338.000000, 213.800003, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, fstd_p[playerid][76], 0.480000, 1.120000);
PlayerTextDrawTextSize(playerid, fstd_p[playerid][76], 58.550858, 30.950008);
PlayerTextDrawAlignment(playerid, fstd_p[playerid][76], 1);
PlayerTextDrawColor(playerid, fstd_p[playerid][76], 0xBFAE56FF);
PlayerTextDrawUseBox(playerid, fstd_p[playerid][76], 0);
PlayerTextDrawBoxColor(playerid, fstd_p[playerid][76], 0x80808080);
PlayerTextDrawSetShadow(playerid, fstd_p[playerid][76], 2);
PlayerTextDrawSetOutline(playerid, fstd_p[playerid][76], 0);
PlayerTextDrawBackgroundColor(playerid, fstd_p[playerid][76], 0x000000FF);
PlayerTextDrawFont(playerid, fstd_p[playerid][76], 4);
PlayerTextDrawSetProportional(playerid, fstd_p[playerid][76], 1);
PlayerTextDrawSetSelectable(playerid, fstd_p[playerid][76], 1);

fstd_p[playerid][75] = CreatePlayerTextDraw(playerid, 367.275421, 223.992050, "MENU");
PlayerTextDrawLetterSize(playerid, fstd_p[playerid][75], 0.188333, 1.056592);
PlayerTextDrawTextSize(playerid, fstd_p[playerid][75], 1280.000000, 1280.000000);
PlayerTextDrawAlignment(playerid, fstd_p[playerid][75], 2);
PlayerTextDrawColor(playerid, fstd_p[playerid][75], 0xFFFFFFFF);
PlayerTextDrawUseBox(playerid, fstd_p[playerid][75], 0);
PlayerTextDrawBoxColor(playerid, fstd_p[playerid][75], 0x80808080);
PlayerTextDrawSetShadow(playerid, fstd_p[playerid][75], 0);
PlayerTextDrawSetOutline(playerid, fstd_p[playerid][75], 0);
PlayerTextDrawBackgroundColor(playerid, fstd_p[playerid][75], 0x00000000);
PlayerTextDrawFont(playerid, fstd_p[playerid][75], 2);
PlayerTextDrawSetProportional(playerid, fstd_p[playerid][75], 1);
PlayerTextDrawSetSelectable(playerid, fstd_p[playerid][75], 0);

29,275421
10,192047

61,550842

29,275421

*/
    for(new i, buttonNames[][][] = { {"MENU"}, {"SETTINGS"}, {"CARS"}, {"BUSINESS"}, {"DONATE"}, {"FAMILY"}, {"QUEST"}, {"REWARDS"} }; i < 16; i++)
    {
        printf("created++ [%i]Info: (%f, %f, %s)", i, 338.000000 + ((i % 2 ? 61.550842 : 29.275421) * i), 223.992050 + (i % 4 ? 33.949997 : 0.0), i % 2 ? "TEXT" : !"LD_SPAC:white");
        inventoryTextdraw[playerid][23 + i] = CreatePlayerTextDraw(playerid, 338.000000 + ((i % 2 ? 61.550842 : 29.275421) * i), 223.992050 + ((i % 4 ? 33.949997 : 0.0) * i), i % 2 ? "TEXT" : !"LD_SPAC:white");
        PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 0.188333 : 0.480000, i % 2 ? 1.056592 : 1.120000);
        PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 1280.000000 : 38.033894, i % 2 ? 1280.000000 : 17.599998);
        PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 2 : 1);
        PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 0xFFFFFFFF : 0xBFAE56FF);
        PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][23 + i], 0);
        PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][23 + i], 0x80808080);
        PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 0 : 2);
        PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][23 + i], 0);
        PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][23 + i], 0x000000FF);
        PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 2 : 4);
        PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][23 + i], 1);
        PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][23 + i], i % 2 ? 0 : 1);
    }

    inventoryTextdraw[playerid][40] = CreatePlayerTextDraw(playerid, 380.024231, 133.600006, "ARM: 0");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][40], 0.125555, 0.704395);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][40], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][40], 3);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][40], 0xAAAAAAFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][40], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][40], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][40], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][40], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][40], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][40], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][40], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][40], 0);

    inventoryTextdraw[playerid][41] = CreatePlayerTextDraw(playerid, 380.024231, 141.643951, "HP: 121");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][41], 0.125555, 0.704395);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][41], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][41], 3);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][41], 0xCD3432FF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][41], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][41], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][41], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][41], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][41], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][41], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][41], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][41], 0);

    inventoryTextdraw[playerid][42] = CreatePlayerTextDraw(playerid, 338.000000, 130.600006, "_");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][42], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][42], 8.500000, 9.833333);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][42], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][42], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][42], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][42], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][42], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][42], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][42], 0x111111FF);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][42], 5);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][42], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][42], 1);
    PlayerTextDrawSetPreviewModel(playerid, inventoryTextdraw[playerid][42], 1649);
    PlayerTextDrawSetPreviewRot(playerid, inventoryTextdraw[playerid][42], 0.000000, 0.000000, 90.000000, 2.000000);

    inventoryTextdraw[playerid][43] = CreatePlayerTextDraw(playerid, 339.672607, 131.743134, "~<~");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][43], 0.134524, 0.754709);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][43], 1280.000000, 1280.000000);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][43], 2);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][43], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][43], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][43], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][43], 0);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][43], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][43], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][43], 2);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][43], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][43], 0);

    inventoryTextdraw[playerid][44] = CreatePlayerTextDraw(playerid, 309.264954, 123.599998, "LD_SPAC:white");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][44], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][44], 90.072655, 89.200005);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][44], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][44], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][44], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][44], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][44], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][44], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][44], 0x33333300);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][44], 5);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][44], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][44], 0);
    PlayerTextDrawSetPreviewModel(playerid, inventoryTextdraw[playerid][44], GetPlayerSkin(playerid));
    PlayerTextDrawSetPreviewRot(playerid, inventoryTextdraw[playerid][44], 0.000000, 0.000000, 0.000000, 1.000000);

    inventoryTextdraw[playerid][45] = CreatePlayerTextDraw(playerid, 346.112854, 160.523346, "LD_SPAC:white");
    PlayerTextDrawLetterSize(playerid, inventoryTextdraw[playerid][45], 0.480000, 1.120000);
    PlayerTextDrawTextSize(playerid, inventoryTextdraw[playerid][45], 16.376846, 15.353293);
    PlayerTextDrawAlignment(playerid, inventoryTextdraw[playerid][45], 1);
    PlayerTextDrawColor(playerid, inventoryTextdraw[playerid][45], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, inventoryTextdraw[playerid][45], 0);
    PlayerTextDrawBoxColor(playerid, inventoryTextdraw[playerid][45], 0x80808080);
    PlayerTextDrawSetShadow(playerid, inventoryTextdraw[playerid][45], 2);
    PlayerTextDrawSetOutline(playerid, inventoryTextdraw[playerid][45], 0);
    PlayerTextDrawBackgroundColor(playerid, inventoryTextdraw[playerid][45], 0x00000000);
    PlayerTextDrawFont(playerid, inventoryTextdraw[playerid][45], 5);
    PlayerTextDrawSetProportional(playerid, inventoryTextdraw[playerid][45], 1);
    PlayerTextDrawSetSelectable(playerid, inventoryTextdraw[playerid][45], 1);
    PlayerTextDrawSetPreviewModel(playerid, inventoryTextdraw[playerid][45], 1314);
    PlayerTextDrawSetPreviewRot(playerid, inventoryTextdraw[playerid][45], 0.000000, 0.000000, 0.000000, 0.721063);